# Generated by Django 4.0.6 on 2022-08-25 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='texto_dois',
            field=models.TextField(default=None, max_length=500, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='about',
            name='texto_um',
            field=models.TextField(default=None, max_length=500, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='about',
            name='titulo_texto_dois',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Titulo da descrição'),
        ),
        migrations.AddField(
            model_name='about',
            name='titulo_texto_um',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Titulo da descrição'),
        ),
        migrations.AlterField(
            model_name='about',
            name='titulo_descricao_pagina',
            field=models.CharField(default=None, max_length=50, null=True, verbose_name='Titulo da descrição'),
        ),
    ]
