# Generated by Django 4.0.6 on 2022-08-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_texto_dois_about_texto_um_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='texto_dois',
            field=models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='about',
            name='texto_um',
            field=models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='about',
            name='titulo_texto_dois',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Titulo da descrição'),
        ),
        migrations.AlterField(
            model_name='about',
            name='titulo_texto_um',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Titulo da descrição'),
        ),
    ]
