# Generated by Django 4.0.6 on 2022-08-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_about_texto_dois_alter_about_texto_um_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='texto_tres',
            field=models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='Texto 3'),
        ),
        migrations.AddField(
            model_name='about',
            name='titulo_texto_tres',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Titulo texto 3'),
        ),
        migrations.AlterField(
            model_name='about',
            name='texto_dois',
            field=models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='Texto 2'),
        ),
        migrations.AlterField(
            model_name='about',
            name='texto_um',
            field=models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='Texto 1'),
        ),
        migrations.AlterField(
            model_name='about',
            name='titulo_texto_dois',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Titulo texto 2'),
        ),
        migrations.AlterField(
            model_name='about',
            name='titulo_texto_um',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Titulo texto 1'),
        ),
    ]
