# Generated by Django 4.0.6 on 2022-08-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_about_texto_tres_about_titulo_texto_tres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='imagem_texto_dois',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_about/imagens_texto_dois', verbose_name='Imagem do texto 2'),
        ),
        migrations.AddField(
            model_name='about',
            name='imagem_texto_tres',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_about/imagens_texte_tres', verbose_name='Imagem do texto 3'),
        ),
        migrations.AddField(
            model_name='about',
            name='imagem_texto_um',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_about/imagens_texto_um', verbose_name='Imagem do texto 1'),
        ),
        migrations.AlterField(
            model_name='about',
            name='imagem_pagina',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_about/imagens_background', verbose_name='Background'),
        ),
    ]
