# Generated by Django 4.0.6 on 2022-08-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='descricao_quadrado_um',
            field=models.TextField(default=None, max_length=500, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='home',
            name='titulo_quadrado_um',
            field=models.CharField(default=None, max_length=50, verbose_name='Título'),
        ),
    ]
