# Generated by Django 4.0.6 on 2022-08-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_descricao_quadrado_um_home_titulo_quadrado_um'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='descricao_quadrado_um',
            field=models.TextField(default='', max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='home',
            name='titulo_pagina',
            field=models.CharField(default='', max_length=50, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='home',
            name='titulo_quadrado_um',
            field=models.CharField(default='', max_length=50, verbose_name='Título'),
        ),
    ]
