# Generated by Django 4.0.6 on 2022-08-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_home_imagem_pagina'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='descricao_pagina',
            field=models.TextField(blank=True, default='None', max_length=500, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='home',
            name='subtitulo_pagina',
            field=models.TextField(blank=True, default='', max_length=50, null=True, verbose_name='Subtítulo'),
        ),
    ]
