# Generated by Django 4.0.6 on 2022-08-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_home_descricao_quadrado_um_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='titulo_quadrado_um',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Título do quadrado 1'),
        ),
    ]
