# Generated by Django 4.0.6 on 2022-08-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_home_titulo_quadrado_um'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='descricao_quadrado_um',
            field=models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='Descrição do quadrado 1'),
        ),
    ]
