# Generated by Django 4.0.6 on 2022-08-23 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_home_descricao_quadrado_um'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='descricao_quadrado_cinco',
            field=models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='Descrição do quadrado 5'),
        ),
        migrations.AddField(
            model_name='home',
            name='descricao_quadrado_dois',
            field=models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='Descrição do quadrado 2'),
        ),
        migrations.AddField(
            model_name='home',
            name='descricao_quadrado_quatro',
            field=models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='Descrição do quadrado 4'),
        ),
        migrations.AddField(
            model_name='home',
            name='descricao_quadrado_tres',
            field=models.TextField(blank=True, default=None, max_length=500, null=True, verbose_name='Descrição do quadrado 3'),
        ),
        migrations.AddField(
            model_name='home',
            name='titulo_quadrado_cinco',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Título do quadrado 5'),
        ),
        migrations.AddField(
            model_name='home',
            name='titulo_quadrado_dois',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Título do quadrado 2'),
        ),
        migrations.AddField(
            model_name='home',
            name='titulo_quadrado_quatro',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Título do quadrado 4'),
        ),
        migrations.AddField(
            model_name='home',
            name='titulo_quadrado_tres',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='Título do quadrado 3'),
        ),
    ]
