# Generated by Django 4.0.6 on 2022-08-23 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_home_icon_quadrado_um'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='icon_quadrado_um',
        ),
    ]
