# Generated by Django 4.0.6 on 2022-08-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_home_icon_quadrado_um'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='descricao_quadrado_cinco',
            field=models.TextField(blank=True, default=None, max_length=200, null=True, verbose_name='Descrição do quadrado 5'),
        ),
        migrations.AlterField(
            model_name='home',
            name='descricao_quadrado_dois',
            field=models.TextField(blank=True, default=None, max_length=200, null=True, verbose_name='Descrição do quadrado 2'),
        ),
        migrations.AlterField(
            model_name='home',
            name='descricao_quadrado_quatro',
            field=models.TextField(blank=True, default=None, max_length=200, null=True, verbose_name='Descrição do quadrado 4'),
        ),
        migrations.AlterField(
            model_name='home',
            name='descricao_quadrado_tres',
            field=models.TextField(blank=True, default=None, max_length=200, null=True, verbose_name='Descrição do quadrado 3'),
        ),
        migrations.AlterField(
            model_name='home',
            name='descricao_quadrado_um',
            field=models.TextField(blank=True, default=None, max_length=200, null=True, verbose_name='Descrição do quadrado 1'),
        ),
    ]
