# Generated by Django 4.0.6 on 2022-08-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_home_descricao_quadrado_cinco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='descricao_quadrado_cinco',
            field=models.TextField(blank=True, default=' ', max_length=200, null=True, verbose_name='Descrição do quadrado 5'),
        ),
        migrations.AlterField(
            model_name='home',
            name='descricao_quadrado_dois',
            field=models.TextField(blank=True, default=' ', max_length=200, null=True, verbose_name='Descrição do quadrado 2'),
        ),
        migrations.AlterField(
            model_name='home',
            name='descricao_quadrado_quatro',
            field=models.TextField(blank=True, default=' ', max_length=200, null=True, verbose_name='Descrição do quadrado 4'),
        ),
        migrations.AlterField(
            model_name='home',
            name='descricao_quadrado_tres',
            field=models.TextField(blank=True, default=' ', max_length=200, null=True, verbose_name='Descrição do quadrado 3'),
        ),
        migrations.AlterField(
            model_name='home',
            name='descricao_quadrado_um',
            field=models.TextField(blank=True, default=' ', max_length=200, null=True, verbose_name='Descrição do quadrado 1'),
        ),
        migrations.AlterField(
            model_name='home',
            name='titulo_quadrado_cinco',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Título do quadrado 5'),
        ),
        migrations.AlterField(
            model_name='home',
            name='titulo_quadrado_dois',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Título do quadrado 2'),
        ),
        migrations.AlterField(
            model_name='home',
            name='titulo_quadrado_quatro',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Título do quadrado 4'),
        ),
        migrations.AlterField(
            model_name='home',
            name='titulo_quadrado_tres',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Título do quadrado 3'),
        ),
        migrations.AlterField(
            model_name='home',
            name='titulo_quadrado_um',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True, verbose_name='Título do quadrado 1'),
        ),
    ]
