# Generated by Django 4.0.6 on 2022-08-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_home_descricao_quadrado_cinco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='titulo_quadrado_um',
            field=models.CharField(blank=True, default='sem titulo', max_length=50, null=True, verbose_name='Título do quadrado 1'),
        ),
    ]
