# Generated by Django 4.0.6 on 2022-08-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_home_titulo_quadrado_um'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='imagem_pagina',
            field=models.ImageField(blank=True, null=True, upload_to='imagens_home/', verbose_name='Background'),
        ),
    ]
